-- =======================================
-- Database, warehouse, schema, role
-- =======================================

-- Database
CREATE DATABASE IF NOT EXISTS COWJACKET;


-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;


-- Schema
CREATE SCHEMA IF NOT EXISTS COWJACKET.RAW;

CREATE SCHEMA IF NOT EXISTS COWJACKET.OBSERVABILITY;

CREATE SCHEMA IF NOT EXISTS COWJACKET.ANALYTICS;

CREATE SCHEMA IF NOT EXISTS COWJACKET.ANALYTICS_MARTS; -- default prod schema


-- Role
CREATE ROLE COWJACKET_DBT_ROLE;


-- =======================================
-- Permissions
-- =======================================

-- Warehouse & Database usage
GRANT ROLE COWJACKET_DBT_ROLE TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE COWJACKET_DBT_WH TO ROLE COWJACKET_DBT_ROLE;

GRANT USAGE ON DATABASE COWJACKET TO ROLE COWJACKET_DBT_ROLE;


-- Schema usage
GRANT USAGE ON SCHEMA COWJACKET.RAW TO ROLE COWJACKET_DBT_ROLE;

GRANT USAGE ON SCHEMA COWJACKET.ANALYTICS TO ROLE COWJACKET_DBT_ROLE;

GRANT USAGE ON SCHEMA COWJACKET.ANALYTICS_MARTS TO ROLE COWJACKET_DBT_ROLE;

GRANT CREATE SCHEMA ON DATABASE COWJACKET TO ROLE COWJACKET_DBT_ROLE;


-- Views & Tables
GRANT CREATE VIEW ON SCHEMA COWJACKET.ANALYTICS TO ROLE COWJACKET_DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA COWJACKET.ANALYTICS TO ROLE COWJACKET_DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA COWJACKET.ANALYTICS_MARTS TO ROLE COWJACKET_DBT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA COWJACKET.RAW TO ROLE COWJACKET_DBT_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA COWJACKET.RAW TO ROLE COWJACKET_DBT_ROLE;